<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Authors\Commands\" />
    <Folder Include="Features\Authors\Queries\" />
    <Folder Include="Features\Books\Commands\" />
    <Folder Include="Features\Categories\Commands\" />
    <Folder Include="Features\Categories\Queries\" />
    <Folder Include="Features\Identity\Commands\" />
    <Folder Include="Features\Books\Queries\" />
    <Folder Include="Features\Identity\Queries\" />
    <Folder Include="Features\Orders\Commands\" />
    <Folder Include="Features\Orders\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
